export const movieData = [
  {
    movieTitle: "The Enchanted Forest",
    director: "Jane Smith",
    producer: "Robert Johnson",
    musicComposer: "Emily Davis",
    casting: ["Chris Evans", "Emma Watson", "Tom Holland"],
    releaseDate: "2024-03-15",
  },
  {
    movieTitle: "Beyond the Stars",
    director: "John Doe",
    producer: "Sarah Brown",
    musicComposer: "Michael Lee",
    casting: ["Zendaya", "Timothee Chalamet", "Oscar Isaac"],
    releaseDate: "2024-06-22",
  },
  {
    movieTitle: "The Last Voyage",
    director: "Sophia Martinez",
    producer: "David Kim",
    musicComposer: "Lucas Wright",
    casting: ["Gal Gadot", "Jason Momoa", "Henry Cavill"],
    releaseDate: "2024-09-10",
  },
  {
    movieTitle: "Echoes of Time",
    director: "Michael Green",
    producer: "Laura Thomas",
    musicComposer: "Anna Bell",
    casting: ["Scarlett Johansson", "Chris Hemsworth", "Mark Ruffalo"],
    releaseDate: "2024-11-05",
  },
  {
    movieTitle: "Shadows in the Mist",
    director: "David Wilson",
    producer: "Sophia Johnson",
    musicComposer: "Emma Carter",
    casting: ["Natalie Portman", "Ewan McGregor", "Liam Neeson"],
    releaseDate: "2025-01-20",
  },
  {
    movieTitle: "Rise of the Guardians",
    director: "Emily Walker",
    producer: "Robert Hall",
    musicComposer: "Oliver Clark",
    casting: ["Tom Hardy", "Anne Hathaway", "Christian Bale"],
    releaseDate: "2024-07-18",
  },
  {
    movieTitle: "Chronicles of Avalon",
    director: "Olivia Harris",
    producer: "William Moore",
    musicComposer: "Sophia Adams",
    casting: ["Jennifer Lawrence", "Bradley Cooper", "Josh Hutcherson"],
    releaseDate: "2024-08-30",
  },
  {
    movieTitle: "The Silent Horizon",
    director: "James Anderson",
    producer: "Maria Lewis",
    musicComposer: "Elijah Miller",
    casting: ["Matt Damon", "Emily Blunt", "Cillian Murphy"],
    releaseDate: "2024-10-15",
  },
  {
    movieTitle: "Dreamcatcher",
    director: "Ella Scott",
    producer: "Alexander White",
    musicComposer: "Isabella Thompson",
    casting: ["Ryan Gosling", "Margot Robbie", "Simu Liu"],
    releaseDate: "2024-12-01",
  },
  {
    movieTitle: "Lost in the Arctic",
    director: "Benjamin Taylor",
    producer: "Grace Roberts",
    musicComposer: "Liam Brown",
    casting: ["Daniel Craig", "Rachel Weisz", "Javier Bardem"],
    releaseDate: "2025-03-07",
  },
  {
    movieTitle: "Warrior's Legacy",
    director: "Charlotte Lewis",
    producer: "Jacob Martinez",
    musicComposer: "Sophia Hernandez",
    casting: ["Dwayne Johnson", "Kevin Hart", "Karen Gillan"],
    releaseDate: "2025-05-15",
  },
  {
    movieTitle: "The Eternal Flame",
    director: "Daniel Clark",
    producer: "Emily Turner",
    musicComposer: "Ava Lopez",
    casting: ["Chris Pratt", "Zoe Saldana", "Dave Bautista"],
    releaseDate: "2025-07-22",
  },
  {
    movieTitle: "Beneath the Surface",
    director: "Sophie Wilson",
    producer: "Liam Walker",
    musicComposer: "Noah Hall",
    casting: ["Jessica Chastain", "Michael Fassbender", "James McAvoy"],
    releaseDate: "2025-10-02",
  },
  {
    movieTitle: "The Vanishing Point",
    director: "Lucas Anderson",
    producer: "Mia Roberts",
    musicComposer: "Ethan Harris",
    casting: ["Jake Gyllenhaal", "Rebecca Ferguson", "Hugh Jackman"],
    releaseDate: "2025-12-11",
  },
  {
    movieTitle: "Whispering Shadows",
    director: "Amelia Martinez",
    producer: "Logan Adams",
    musicComposer: "Charlotte King",
    casting: ["Viola Davis", "Octavia Spencer", "Mahershala Ali"],
    releaseDate: "2026-02-18",
  },
  {
    movieTitle: "The Forgotten Realm",
    director: "Jackson Evans",
    producer: "Ava Harris",
    musicComposer: "Oliver Scott",
    casting: ["Benedict Cumberbatch", "Martin Freeman", "Andrew Scott"],
    releaseDate: "2026-04-09",
  },
  {
    movieTitle: "Fragments of Destiny",
    director: "Harper Wright",
    producer: "Ethan Lewis",
    musicComposer: "Grace Walker",
    casting: ["Keanu Reeves", "Carrie-Anne Moss", "Laurence Fishburne"],
    releaseDate: "2026-06-22",
  },
  {
    movieTitle: "Twilight of the Gods",
    director: "Oliver Clark",
    producer: "Isabella White",
    musicComposer: "Emma Thompson",
    casting: ["Tom Hiddleston", "Cate Blanchett", "Idris Elba"],
    releaseDate: "2026-08-12",
  },
  {
    movieTitle: "Celestial Chronicles",
    director: "William Harris",
    producer: "Sophia Green",
    musicComposer: "James Martinez",
    casting: ["Eddie Redmayne", "Katherine Waterston", "Ezra Miller"],
    releaseDate: "2026-10-25",
  },
  {
    movieTitle: "The Shadow's Edge",
    director: "Emma Robinson",
    producer: "Benjamin Scott",
    musicComposer: "Mia Walker",
    casting: ["Hugh Grant", "Nicole Kidman", "Colin Firth"],
    releaseDate: "2026-12-17",
  },
];
